### ISSUE TITLE
Facebook error: You have not defined a path for the route alias postLoginPath.

### ISSUE THREAD

**Issue by ghost** [bnoguchi/mongoose-auth#1]
When using the Facebook module, I get the following error:

```
Error: You have not defined a path for the route alias postLoginPath.
at Object.routeApp (/usr/lib/node/.npm/everyauth/0.0.9/package/lib/everymodule.js:173:19)
at Function.<anonymous> (/usr/lib/node/.npm/everyauth/0.0.9/package/index.js:38:41)
at Function.router (/usr/lib/node/.npm/connect/1.3.0/package/lib/middleware/router.js:94:6)
at Function.middleware (/usr/lib/node/.npm/everyauth/0.0.9/package/index.js:33:15)
at HTTPServer.<anonymous> (/Users/jason/Sites/tixelated/app.js:77:20)
at HTTPServer.configure (/Users/jason/node_modules/.npm/express/2.0.0/package/lib/http.js:422:8)
at Object.<anonymous> (/Users/jason/Sites/tixelated/app.js:46:5)
at Module._compile (module.js:383:26)
at Object..js (module.js:389:10)
at Module.load (module.js:315:31)
```

Invocation:

```
var UserSchema = new Schema({
  username         : String,
  first_name       : String,
  middle_name      : String,
  last_name        : String,
  type             : Number,
  admin            : Number                                                                                                                                                    
});
UserSchema.plugin(useTimestamps);
UserSchema.plugin(mod_mongooseAuth, {
  facebook : { everyauth : settings.everyauth.facebook }
});
```

Configs (settings.everyauth.facebook):

```
{
  appId           : 'xxxxxxxxxxxxxx'
  , appSecret     : 'xxxxxxxxxxxxxxxxxxx'
  , scope         : 'email'
  , redirectPath  : '/'
  , entryPath     : '/auth/facebook'
  , callbackPath  : '/auth/facebook/callback'
}
```

**Comment by tixelated** [comment]
I'm using:

mongoose-auth@0.0.5
everyauth@0.0.9
oauth@0.9.0
connect@1.3.0
mongoose@1.2.0

**Comment by tixelated** [comment]
Oh yeah - node@0.4.2/express@2.2.2

It's happening, of course, when setting up the routes:

```
mod_mongoose = require('mongoose');
mod_mongooseAuth  = require("mongoose-auth");

app = module.exports = mod_express.createServer();

app.configure(function(){
  ...
  mod_mongooseAuth.middleware();
});
```

**Comment by bnoguchi** [comment]
Thanks for notifying me of the Issue. The bug is that the code loads ALL of the modules. I just pushed a fix for this. Now, modules are only enabled when you first access them via everyauth like:

```
everyauth.facebook;
```

Or via mongoose-auth like:

```
schema.plugin(mongooseAuth, {
    facebook: {
        everyauth: {...}
    }
}); // i.e., the modules that are now enabled are the keys of this Object -- i.e., `facebook`
```

Should be everyauth v0.0.10 now via npm install.

**Comment by tixelated** [comment]
Thanks! Makes sense. I just did a quick npm update of everyauth (verified @0.0.10) and am getting the same error, but I'll dig in a little later and confirm if it's still an issue or not.

**Comment by bnoguchi** [comment]
Can you send me a gist?

**Comment by liamdon** [comment]
This was giving me trouble today as well - it works via everyauth but not via mongoose-auth.

I propose the following fix:
https://github.com/bnoguchi/mongoose-auth/pull/2/files

**Comment by bnoguchi** [comment]
mongoose-auth does not need a patch. The issue lies with everyauth. I just fixed this completely this time. Install everyauth v0.1.0 via

```
$ npm install everyauth
```

**Comment by tixelated** [comment]
Thanks - seems to be working now (at least not crashing on startup.) I also
noticed that node was still using the older 0.9.0 everyauth when I followed
up, have upgraded/forced 0.1.0 and it's looking good, thanks.

Jason Bond Pratt
President/CTO, Tixelated
202.841.8396
http://tixelated.com/jason@tixelated.com

http://tixelated.com/
http://tixelated.com/ jason@tixelated.comhttp://tixelated.com
http://twitter.com/tixelated
