### ISSUE TITLE
Login with email

### ISSUE THREAD

**Issue by cayasso** [bnoguchi/mongoose-auth#10]
Hi Brian, I am currently working on an application where the User model will be highly used to store medical records and locations, User can login with facebook or twitter and then create an account  with email, phone, first name and last name, so if user is logged in with FB they will be prompted to create an account with the fields above however if the user doesnt have twitter or facebook they will need to register an account with above fields(username would the email) plus a password for login.

Currently login is the default key for the username, but instead of login I would like to use email, so user can logon just with their email. Is their an easy way to do this change.

What is the best way to add more fields to the build in registration, so for example I would like to add firstName, lastName and Phone?. Do I need to create my own registration or is there a way to overwrite the default and use mine way of registering.

Any good suggestion to handle the above scenario?

Thank you for such a great node module.

**Comment by bnoguchi** [comment]
I'm pushing out a new version of everyauth and mongoose-auth tomorrow morning with more powerful registration configuration (been playing around with different APIs this last week). You'll be able to accomplish everything you will ever want with registration tomorrow morning. Check back then, and in the meantime make sure to follow me or the project, so you get informed every time I update the version (which I expect to be often at least for the next 2 weeks leading up to an official announcement of a stable release).

**Comment by cayasso** [comment]
Thank you for the quick response Brian, thats a great news, if the existing version to me is great I cant wait to see the improved one tomorrow.

Thank and I will keep my eyes on!!!

JB

**Comment by bnoguchi** [comment]
Done, with recipes in the README for what you are looking to do.

**Comment by cayasso** [comment]
Wow this is fantastic, thank you for your dedication, I am upgrading right now.
Thanks!

**Comment by cayasso** [comment]
Hey Brian a last question, I would like to use my own User model, this because I have to add some other information like medical records, activation token, medications, etc these extra fields has validation also, is there a way to connect everyauth with mongoose-auth to use custom User model, where fields can be added at any moment when user is already loggedin? or I can even update the User with a different interface.

Thank you again!
JB

**Comment by cayasso** [comment]
I think I almost got the answer to my own question, I will play a bit more with this.

**Comment by bnoguchi** [comment]
Yeah, with mongoose-auth, you start off with your own UserSchema and are just augmenting it with mongoose-auth plugin:

``` javascript
 UserSchema.plugin(mongooseAuth, {
       //...
```

mongoose-auth only adds fields to your UserSchema, it does not over-write your UserSchema. So you just define your UserSchema before-hand with all the attributes you want.
