### ISSUE TITLE
it won't work when express.session({ secret: 'esoognom'})  in app.use() to configure express app.

### ISSUE THREAD

**Issue by bewa** [bnoguchi/mongoose-auth#12]
I'm a newbie of express.js dev and also node.js
So I wonder whether this would be a bug of mongoose-auth .

I follow the examples in the git repo like follwing,it works perfect.

```
var app = module.exports = express.createServer(
    express.bodyParser()
  , express.static(__dirname + "/public")
  , express.cookieParser()
  , express.session({ secret: 'esoognom'})
);
```

but when I use configure, the req.sess in the mongooseAuth.middleware() (I trace it to everyauth.middleware()) is undifined.

```
app.configure(function(){
  app.set('views', __dirname + '/views');
  app.set('view engine', 'jade');
  app.use(express.methodOverride());
  app.use(express.session({ secret: 'esoognom'}));
  app.use(app.router);
});
```

Would it be a bug?

**Comment by bewa** [comment]
And when I write following,it won't work either.

---

server.js is like this :

```
var app = module.exports = express.createServer(
  express.cookieParser()
 ,express.session({ secret: 'your secret here' })
);
require(app_path + 'app/controllers.js');

app.listen(3000);
```

---

controller.js is like this:

```
var app = module.parent.exports;
var mongooseAuth = require('mongoose-auth');
app.use( mongooseAuth.middleware());
mongooseAuth.helpExpress(app);
```

---

it can regiter and login. but can't get user.id after login.

**Comment by bnoguchi** [comment]
Can you send me a https://gist.github.com how you're trying to access user from your controller? Or, better yet, a single file that I can just run once to replicate the error? I cannot reproduce this issue on my machine.

**Comment by bnoguchi** [comment]
Also, please copy/paste your stacktrace here.

**Comment by bnoguchi** [comment]
e6nian, check your inbox for how to correct your code. But basically, you should not explicitly use `app.router` as declared middleware. If you remove the following line, everything should work:

```
app.use(app.router);
```

--Brian
