### ISSUE TITLE
Twitter not working?

### ISSUE THREAD

**Issue by tblobaum** [bnoguchi/mongoose-auth#13]
I can't seem to get twitter to authenticate.  It gets back to the homepage with a url string but goes no further.  No errors or anything.  Github works though...

**Comment by bnoguchi** [comment]
It works for me.

Can you make sure debug is turned on?

``` javascript
var everyauth = require('everyauth');
everyauth.debug = true;
```

Then send me the output from your console.

--Brian

**Comment by bnoguchi** [comment]
Also, make sure you are using "local.host:3000", not "localhost:3000", if you are trying to run the example. See the everyauth README for how to set this up.
