### ISSUE TITLE
Create and confirming account before saving

### ISSUE THREAD

**Issue by cayasso** [bnoguchi/mongoose-auth#15]
Hi Brian, I need some help with this scenario. Its a user first visit to my app and he login with FB user, at this point I would like to redirect the user to register screen where he can create a name, last name, user name(his email) and a password, he would need to type it, I can use FB to populate the first and last name and the username based on email,  and let the user to choose if he really want that email address as login. In the example that you have for linking accounts, it assumes that the user is already created, but in this case I am creating a user based on FB account and would like the user to confirm before saving. Is there an easy way to do this interruption and not having to do it in a after screen.

Thank you in advance for your help!

JB

**Comment by bnoguchi** [comment]
Why not create the user before the basic info + password choosing steps?

I would let mongoose-auth create the user for you via the facebook module's default behavior. If you do not want this to happen, it is configurable, and I can tell you how; but for the sake of simplicity, I would again question the requirement that you can't save your user after Facebook OAuth.

For implementing the rest of your desired scenario, you can set facebook's everyauth.redirectPath to '/register'. Then, you can over-ride `displayRegister` via:

``` javascript

password: {
  everyauth: {
    ...,
    displayRegister: function (req, res) {
      var user = req.user;
      var userParams = {};
      if (user && user.fb && user.fb.id) userParams.email = user.fb.email;
      if (user && user.fb && user.fb.id) userParams.name.first = user.fb.name.first;
      res.render('register', { userParams: userParams });
    }),
    ...
```

Once that's done, just follow the approach as outlined in my account linking example.

--Brian

**Comment by cayasso** [comment]
Thanks Brian for the solution above!!!

Sorry for bringing this again (I dont meant to be a pain in the @$$$), consider these use cases.
1. User first got to the page and create his account with regular email and password, next time he come to his application he also see the option to login with facebook, he then try to login with facebook instead of using his email and password. For this practical case the app should sign in the user with FB and then ask to link account (by asking for email and password) with his existing account(this before saving facebook to the DB) once user enter an email and a password and if this is valid then FB account is saved under the user existing account. 
2. User first go to the page and create his account with Facebook, next time he come to the app he want's to signin with regular email and password, since he only created a FB account there is no email nor password attached to his account therefor he needs a way in advance to confirm his email and create his password linked to his FB account. So right after user clicks "sign in with FB" then before saving, the app would need to ask the user to enter email and password (before FB data is saved to the DB, because account can already exist) to complete his registration.

In general I think it would be ideal for mongoose-auth (or maybe this is a feature request for everyauth) should provide an easy way to just signin and be able to retrieve FB data for later saving. I think this would be a a practical feature and would help others.

I hope all the above make sense, you can check the Yahoo login page for an example https://login.yahoo.com/ sign in with Facebook and you should see what I mean.

Can you tell me what would be the best way to implement a solution for the cases above, I am struggleling on finding a good implementation with mongoose-auth without having to do some code rewrite :(, so any help would be appreciated!!!!

Thank you again!
JB

**Comment by dkarigithu** [comment]
First off Bryan,
Hats of to you on this lovely module, however, I'm experiencing the same use case problem as JB did and wondering if you'd managed to find a work around a year later.

Thanks
DK
