### ISSUE TITLE
Problem using email in password authorization strategy

### ISSUE THREAD

**Issue by Migrate** [bnoguchi/mongoose-auth#19]
Hi,

I'm trying to use the password authorization strategy with an email field instead of the login field.
I've added the following code to my schema js file but it does not work. 

```
var UserSchema = new Schema({
        email  : { type: String, index: { unique: true}}
        , password  : String
  }), User;
UserSchema.plugin(mongooseAuth, {
    // Here, we attach your User model to every module
    everymodule: {
      everyauth: {
          User: function () {
            return User;
          }   
      }   
    }   
    , password: {
          // THIS NEXT LINE IS THE ONLY ADDITION
          loginWith: 'email' // Or loginWith: 'phone'

        , everyauth: {
              getLoginPath: '/login'
            , postLoginPath: '/login'
            , loginView: 'login.jade'
            , getRegisterPath: '/register'
            , postRegisterPath: '/register'
            , registerView: 'register.jade'
            , loginSuccessRedirect: '/' 
            , registerSuccessRedirect: '/' 
          }   
      }   
}); 
mongoose.model('User', UserSchema);
```

When I try to start the server I get always the error bellow:

```
node.js:134
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
TypeError: Object function String() { [native code] } has no method 'get'
    at /.../node_modules/mongoose-auth/lib/modules/password/plugin.js:35:30
    at /.../node_modules/mongoose-auth/index.js:73:5
    at Array.forEach (native)
    at plugin (/.../node_modules/mongoose-auth/index.js:36:6)
    at Schema.plugin (/.../node_modules/mongoose/lib/mongoose/schema.js:277:3)
    at Object.make (/.../database_schema.js:50:13)
    at Object.<anonymous> (/.../controllers/main.js:6:36)
    at Module._compile (module.js:404:26)
    at Object..js (module.js:410:10)
    at Module.load (module.js:336:31)
```

Can you please tell me if I'm doing something wrong or if this a bug in the plugin.

Thanks.
Best regards,
Migrate

**Comment by bnoguchi** [comment]
There is built in support for logging in via email (in lieu of login) already in mongoose-auth. Please refer to the README and Ctrl-f for "Recipe 2: Configuring Email or Phone to be your Login for the Password Module"

--Brian

**Comment by Migrate** [comment]
Hi Brain,

That was what I did. I follow recipe 2 as you can see in the example above. Am I doing something wrong?

Thanks again for your help.
Best regards,
Migrate

**Comment by bnoguchi** [comment]
You do not need to declare email and password with your UserSchema because mongoose-auth does this for you automatically. In other words:

```
var UserSchema = new Schema({}), User;
```

Try that and let me know if you're still having problems.

**Comment by bnoguchi** [comment]
Also make sure you're on the latest version of mongoose (1.3.6).

**Comment by Migrate** [comment]
Thanks for your help!
Now its working!
