### ISSUE TITLE
has no method 'middleware'

### ISSUE THREAD

**Issue by geetarista** [bnoguchi/mongoose-auth#20]
I can't get mongoose-auth to work with my Express server:

```
var app = express.createServer(
  mongooseAuth.middleware()
)
```

I get the output of the entire mongoose-auth file and then it says "has no method 'middleware'". I get the same thing when I try to access helpExpress() from within the node REPL.

Am I missing something? I went through the README several times and can't see where I may have gone wrong.

**Comment by bnoguchi** [comment]
Can you create a self-contained [gist](https://gist.github.com/), so that I can re-create this issue independently on my machine?

--Brian

**Comment by geetarista** [comment]
Sorry, but this was my fault. I was able to get it to work just fine. Thanks for getting back to me so quickly, though!

**Comment by christopherdebeer** [comment]
@geetarista , I'm having the same problem, could you please explain what the issue was. thanks in advance.

**Comment by geetarista** [comment]
@christopherdebeer I honestly don't remember exactly what it was, but I remember that it was something I missed in the documentation, which is why I didn't post it here.

**Comment by dmmalam** [comment]
I have the same issue, did you remember what is missing?

**Comment by bnoguchi** [comment]
@christopherdebeer @dmmalam Can you share [gists](https://gist.github.com/) of your code here, so I can help you out?

**Comment by dmmalam** [comment]
This was solved by initializing mongo BEFORE configuring express

**Comment by christopherdebeer** [comment]
@dmmalam thanks, I ended-up just using every-auth and mongoose (not mongoose-auth), but i'll look back into it.

**Comment by tsabolov** [comment]
I have spent a bunch of time trying to solve the problem. At last I looked into the mongoose-auth source.
The reason of such a behavior is that the module exports a function (`plugin`). Extending the module with everyauth methods (`middleware` and `helpExpress`) is performed **INSIDE** of the exported function (see source — https://github.com/bnoguchi/mongoose-auth/blob/master/index.js#L78)
So the only obvious way to use those methods is to invoke a mongoose-auth's exported function at least once.
Let me show (assuming `server` is express or connect server):

The following WILL work:

``` javascript
var mongoose = require('mongoose'),
    Schema = mongoose.Schema,
    mongooseAuth = require('mongoose-auth');

...

var UserSchema = new Schema({});
UserSchema.plugin(mongooseAuth, {
    facebook: true
});

...

server.use(mongoose.middleware());
```

The following WILL NOT work:

``` javascript
var mongoose = require('mongoose'),
    Schema = mongoose.Schema,
    mongooseAuth = require('mongoose-auth');
...

server.use(mongoose.middleware());

...

var UserSchema = new Schema({});
UserSchema.plugin(mongooseAuth, {
    facebook: true
});
```

**Comment by paulshapiro** [comment]
@tsabolov any progress, or any info about whether a fix is coming?

**Comment by tsabolov** [comment]
@paulshapiro As I am not the author of this project, I absolutely have no idea about when it will be fixed.
For myself I have fixed it the following way:
At the very end of the file /index.js there are such a lines:

``` javascript
  // Delegate middleware method to
  // everyauth's middleware method
  exports.middleware = everyauth.middleware.bind(everyauth);

  // Delegate helpExpress method to everyauth.
  // Adds dynamic helpers such as loggedIn,
  // accessible from the views
  exports.helpExpress = everyauth.helpExpress.bind(everyauth);
};
```

To make the module work with just requiring it move exporting of function out of the function just like below:

``` javascript
};
// Delegate middleware method to
// everyauth's middleware method
exports.middleware = everyauth.middleware.bind(everyauth);

// Delegate helpExpress method to everyauth.
// Adds dynamic helpers such as loggedIn,
// accessible from the views
exports.helpExpress = everyauth.helpExpress.bind(everyauth); /* NOW THIS IS THE LAST LINE IN THE index.js */
```

**Comment by paulshapiro** [comment]
@tsabolov, ic, thanks. will keep this in mind.

**Comment by willnathan** [comment]
@tsabolov Thanks for your comment! I adjusted the schema placement, and it ran like a charm.

**Comment by ppcano** [comment]
@tsabolov, npm package 0.0.11 which is the current master version, is working in my case without updating the changes your mention. 

I could get all working well when i follow the configuration steps on the correct order.
