### ISSUE TITLE
Unable to authenticate with twitter

### ISSUE THREAD

**Issue by cayasso** [bnoguchi/mongoose-auth#21]
hi Brian, for some reason I am unable to authenticate with twitter, I keep getting the Authorize app screen on twitter, even if I click on Authorize, 

this is my twitter everyauth setup

<pre>
, twitter: {
      everyauth: {
          //callbackPath: '/users',
          myHostname: 'http://localhost.com:3000'
        , consumerKey: 'xxxxxxxx'
        , consumerSecret: 'xxxxxxxxx'
        , redirectPath: '/users'
      }
    }/*
</pre>

consumer key and secret is ok I already verified it.

This is the debug output

<pre>
starting step - getRequestToken
...finished step
starting step - storeRequestToken
...finished step
starting step - redirectToProviderAuth
...finished step
starting step - getRequestToken
...finished step
starting step - storeRequestToken
...finished step
starting step - redirectToProviderAuth
...finished step
</pre>

I am able to authenticate with facebook with no problem. I am using everyauth 0.2.4 and mongoose auth 0.0.9

Any ideas?

Thanks!

**Comment by bnoguchi** [comment]
What are your configured parameters for your app as you've set them on twitter.com?

**Comment by bnoguchi** [comment]
In particular, what is the "Registered Callback URL" set to? Based on how you configured everyauth, it should be:

http://localhost.com:3000/auth/twitter/callback/

**Comment by adamghill** [comment]
I couldn't get localhost to work, but local.host with an entry in my hosts file worked fine for me. Have you tried that, @cayasso?

**Comment by cayasso** [comment]
@adamghill I have it setup up to localhost.com instead of local.host, it should work ok with that too as long as you setup the same domain in twitter, it has to have an extension .com .host, etc.

@bnoguchi I had a different callback url, I will change it to the one I have setup in my app http://localhost.com:3000/auth/twitter/callback and let you know the outcome.

Thanks

**Comment by cayasso** [comment]
Nice! @bnoguchi I did the change and now I am able to connect and authenticate. Thank you again!!!

JB

**Comment by cayasso** [comment]
@bnoguchi I just noticed that whenever I authenticate with twitter, even if I already logged in (in twitter) and authorized the application I continue to get the "Authorize app" screen on twitter each time I try to login to my app. Any ideas what could be causing the authentication to not be persistent?

JB

**Comment by dustyneuron** [comment]
I'm more than a month late, but just stumbled upon the same problem as @cayasso (kept requiring authorization).
For future readers, the solution is to use twitters oauth/authenticate URL rather than the authorize one (as per https://dev.twitter.com/docs/auth/sign-in-with-twitter).

You can do this in mongoose-auth with:
`authorizePath:  '/oauth/authenticate',`
in your twitter/everyauth schema config.

**Comment by bnoguchi** [comment]
@dustyneuron Thanks. I just changed the default to /oauth/authenticate for the twitter module. It'll make its way into the next everyauth release on npm, so mongoose-auth should have it by default, too, via everyauth.

**Comment by dustyneuron** [comment]
@bnoguchi Great, ta!
