### ISSUE TITLE
mongoose-auth and connect-form

### ISSUE THREAD

**Issue by Migrate** [bnoguchi/mongoose-auth#23]
Hi,

I have an upload form that works fine, but when I add mongoose-auth it stops working. The "req.form.complete" is never called and the server hangs. Can you please help me?

Code: https://gist.github.com/1006435
Note: Upload function is change_image

Thanks again.
Best regards,
Migrate

**Comment by bnoguchi** [comment]
Try removing

``` javascript
app.use(app.router);
```

Let me know if that works.

**Comment by Migrate** [comment]
Hi Brain,

Unfortunately it didn't work.

Best regards,
Migrate

**Comment by bnoguchi** [comment]
Can you update the gist with the additional files I'd need to try running this in my own sandbox? I'd like to re-create the issue on my machine. Thanks.

--Brian

**Comment by ghjunior** [comment]
Hey Brian, ran into this today as well while testing out connect-form (node-formidable) and mongoose-auth, here is a gist of both "merged examples" to reproduce:

https://gist.github.com/1009535

Upload should work when not logged in, fails when logged in. Will continue looking into over here as well. By the way, awesome work on these auth modules!

Cheers,
Greg

**Comment by bnoguchi** [comment]
As a quick fix, change the following lines:

``` javascript
app.post('/', function(req, res, next){
```

to

``` javascript
app.post('/upload', function(req, res, next){
```

AND

``` javascript
        + '<form method="post" enctype="multipart/form-data">'
```

to

``` javascript
        + '<form method="post" action="/upload" enctype="multipart/form-data">'
```

**Comment by bnoguchi** [comment]
Ignore my last comment. I tracked down what was causing this in `everyauth`. npm install the latest everyauth, and it should work, now.

**Comment by ghjunior** [comment]
Sweet, working good, thanks Brian.

**Comment by Migrate** [comment]
Thanks Brian!
I will test it tomorrow.

**Comment by Migrate** [comment]
Hi Brian,

Its working!

Thanks for your help.
