### ISSUE TITLE
Twitter auth not working

### ISSUE THREAD

**Issue by wmdmark** [bnoguchi/mongoose-auth#26]
I've successfully got Facebook logins working however Twitter auth is not. 
The first phase of the oAuth seems to be working just fine but when twitter comes back with the oauth_token and oauth_verifier the app seems to be completely ignoring that. No debug logs from everyauth at all.

Here's my twitter config:

``` javascript
    twitter: {
      everyauth: {
        myHostname: 'http://wmd.local:3000',
        consumerKey: conf.twit.consumerKey,
        consumerSecret: conf.twit.consumerSecret,
        redirectPath: '/'
      }
    }
```

Let me know if there's any other info I can share that might be helpful here.

**Comment by bnoguchi** [comment]
What did you set for your callback url at dev.twitter.com? It should be http://wmd.local:3000/auth/twitter/callback

**Comment by wmdmark** [comment]
Yep, that was the problem. Would be nice if there's was some documentation on that. Maybe I'm just missing it.  

Getting closer now but now I'm getting this error:

```
starting step - rememberTokenSecret
Error: Step rememberTokenSecret of `twitter` is promising: requestTokenSecret ; however, the step returns nothing. Fix the step by returning the expected values OR by returning a Promise that promises said values.
```

**Comment by bnoguchi** [comment]
Can you copy/paste your code, including connect/express middleware setup? You shouldn't be getting an error like this. My hunch is that perhaps you are not including the connect/express session middleware.

--Brian

**Comment by wmdmark** [comment]
Turns out my MongoDB server was not running. Doh.

Sorry for the hassle!
