### ISSUE TITLE
Linkedin and Google login

### ISSUE THREAD

**Issue by tblobaum** [bnoguchi/mongoose-auth#28]
Is it currently possible to use google/linkedin with mongoose-auth?  I noticed they are on the everyauth docs, is it just a matter of configuring them?

**Comment by bnoguchi** [comment]
Not currently built-in to mongoose-auth. But yes, this is just a matter of porting it over from everyauth. If you want to submit pull requests for this, I'd be happy to merge them in. LinkedIn has a lot of fields, so it may take longer. Google should be fairly straightforward.
