### ISSUE TITLE
req.user is undefined though everything appears to be working

### ISSUE THREAD

**Issue by mattmcmanus** [bnoguchi/mongoose-auth#29]
Hey Brian, 

I'm running into a confusing issue. I've got a feeling it's a everyauth issue but I'm using mongooseAuth so I'm positing it here. 

Everything is working fine for logging in and creating users. I can login via twitter or the password module and things seem to be working fine. The only issue is that is that req.user is undefined. I could just set this myself but since I know it's supposed to do this I wanted to let you know. 

Here is my model code:
https://github.com/mattmcmanus/statusQuo/blob/express-mongoose/models.js#L11

I'm running express 2.3.12, everyauth 0.2.12, mongoose-auth 0.0.11

Please let me know if there is anything else you need. I'm not sure what else to give you at this point.

**Comment by bnoguchi** [comment]
Can you confirm access to req.user in the example app that comes with mongoose-auth? There, `req.user` is present once logged in.

**Comment by mattmcmanus** [comment]
Well, after getting your example working right and removing most everything in my app to reflect the example app I figured out what my problem was. In my app.configure I has app.use(app.router). Once I remove that, req.user is there. 

You can check out my test file. https://gist.github.com/1051647/f87533d8f31c9f7780a87fae24e515389673e18d#file_test.js

**Comment by bnoguchi** [comment]
Just added a note to the README to steer people away from including app.router in their express configuration.
