### ISSUE TITLE
Suddenly unable to register new users

### ISSUE THREAD

**Issue by tblobaum** [bnoguchi/mongoose-auth#32]
Session data looks OK.  Here it is.

``` javascript
{ data: {
      "lastAccess":1310210912086
     ,"cookie":{
          "originalMaxAge":14400000
         ,"expires":"2011-07-09T15:28:32.683Z"
         ,"httpOnly":true
         ,"path":"/"
       }
     ,"flash":{}
  },
  _id: 4e1836543c79656dd465fc59,
  sid: '4kX7OEk3Jo4IZ9xICMaMZZKv.7tkCXX+0ZPQg3Y56SOtCgx5W2ZgVdWBP4+MQ8lUKFts',
  expires: Sat, 09 Jul 2011 15:28:32 GMT }
```

And here's the console log...
starting step - extractLoginPassword
...finished step
starting step - extractExtraRegistrationParams
...finished step
starting step - aggregateParams
...finished step
starting step - validateRegistrationBase
...finished step
starting step - validateRegistration
...finished step
starting step - maybeBreakToRegistrationFailSteps
...finished step
starting step - registerUser
{ stack: [Getter/Setter],
  arguments: undefined,
  type: undefined,
  message: 'E11000 duplicate key error index: dev.users.$login_1  dup key: { : null }' }
...finished step
starting step - extractUserOrHandleErrors
breaking out to registrationFailSteps
starting step - respondToRegistrationFail
...finished step

Can't register any new users.  Bit of a headache!  I'm trying to track down the relevant loc myself but if you have any tips I'd really appreciate.

Thanks for all the hard work Brian

**Comment by tblobaum** [comment]
This might actually be an issue I'm having with everyauth

**Comment by tblobaum** [comment]
I slipped this function in to see if params are getting to regiserUser, and they are in the format { email: 'example@email.com', password: 'pass' } -- seems to fail at the `User()().create` method

``` javascript
registerUser: function (newUserAttrs) {
    console.log(newUserAttrs);
    var promise = this.Promise();
    this.User()().create(newUserAttrs, function (err, createdUser) {
        console.log(createdUser);
        if (err) {
            if (/duplicate key/.test(err)) {
                return promise.fulfill(['Someone has already registered with that email.']);
            }
            return promise.fail(err);
        }
        promise.fulfill(createdUser);
    });
    return promise;
}
```

**Comment by bnoguchi** [comment]
What are the versions of your dependencies -- i.e., versions of mongoose, etc.?

**Comment by tblobaum** [comment]
All bleeding edge as far as I know.. here's the literal stack

├── express-messages@0.0.2
├── express-mongoose@0.0.2
├── geoip@0.4.1
├─┬ hashish@0.0.3
│ └── traverse@0.4.3
├── jade@0.10.7
├── mongodb@0.9.6-2  invalid
├─┬ mongoose@1.3.7
│ └── hooks@0.1.9
├─┬ mongoose-auth@0.0.11
│ └─┬ mongoose@1.6.0
│   └── hooks@0.1.9
├─┬ mongoose-types@1.0.3
│ ├─┬ mongoose@1.5.0
│ │ └── hooks@0.1.9
│ └── should@0.2.1  extraneous
├── redis@0.6.6
├─┬ session-mongoose@0.0.1  extraneous
│ └── mongeese@0.0.1
├── uglify-js@1.0.4
├── underscore@1.1.6
└─┬ vows@0.5.8
  └── eyes@0.1.6

**Comment by bnoguchi** [comment]
Based on your console.log output, it seems that you are trying to register a user with the same email, which is causing mongodb and mongoose to throw a unique index violation on the unique login index.

**Comment by tblobaum** [comment]
Yeah thats what I thought, right?

I've put a number of hours into solving this, so I'm probably going to feel pretty silly when its solved.

'E11000 duplicate key error index: dev.users.$login_1 dup key: { : null }' }

Shouldnt this list the attempted insertion instead of { : null } -- I get the feeling a variable is being dropped somewhere and its just trying to register null's over and over.  This sort of makes sense, because if I delete the last registered user? I can register one more.  Then no matter what email we try, it throws a duplicate key error.

**Comment by bnoguchi** [comment]
Can you make a minimal, self-contained [gist](https://gist.github.com/), so I can re-create this issue on my machine. Then, I can really help you out.

**Comment by tblobaum** [comment]
Consider this closed.  Not entirely silly but pretty close heh.  I've been working with getting all logins in everyauth into mongoose-auth AND having them all connect together, and it appears there was a unique key set in the mongoose schema of one of them (which was never defined, and always set to null) so it was failing at that point.  I'll remember to examine all fields in mongoose and mongo for unique keys in the future.

**Comment by tblobaum** [comment]
Thanks for your patience Brian!

**Comment by bnoguchi** [comment]
Cool. Glad you got it resolved.

**Comment by 0m15** [comment]
Hi, I'm experiencing the same issue, even using the included example/server.js app.

Here's my dependencies stack (sorry for the long list):

```
├── JSON@1.0.0 
├── bcrypt@0.4.1 
├─┬ everyauth@0.2.29 
│ ├─┬ connect@1.8.5 
│ │ ├── formidable@1.0.8 
│ │ ├── mime@1.2.4 
│ │ └── qs@0.4.1 
│ ├── node-swt@0.1.1 
│ ├── node-wsfederation@0.1.1 
│ ├── oauth@0.9.5 
│ ├── openid@0.3.2 
│ ├── request@2.9.100 
│ ├── restler@0.2.5 
│ └─┬ xml2js@0.1.13 
│   └── sax@0.3.5 
├─┬ express@2.5.1 
│ ├─┬ connect@1.8.5 
│ │ └── formidable@1.0.8 
│ ├── mime@1.2.4 
│ ├── mkdirp@0.0.7 
│ └── qs@0.4.1 
├─┬ jade@0.20.0  extraneous
│ ├── commander@0.2.1 
│ └── mkdirp@0.3.0 
├─┬ mongoose@2.5.2 
│ ├── hooks@0.1.9 
│ └── mongodb@0.9.7-3-5 
├─┬ mongoose-auth@0.0.11 
│ └── mongoose-types@1.0.3 
└── underscore@1.3.1
```

The mongodb error:

```
MongoError: E11000 duplicate key error index: example.users.$username_1  dup key: { : null }
```

This is the flow:

```
1) Login with Facebook with user 'foo' -> all ok
2) Logout from the site and facebook
3) Login again on the site with user 'bar' -> duplicate key error
```

**Comment by adamburmister** [comment]
I'm getting the same "E11000 duplicate key error index" issue when using Twitter, Facebook, Google, Password. Any resolution to this?

**Comment by catilac** [comment]
Apparently this is by design in Mongoose. https://github.com/LearnBoost/mongoose/issues/508#issuecomment-5731362
