### ISSUE TITLE
Error: Step findOrCreateUser of `facebook` module timed out.

### ISSUE THREAD

**Issue by jamiltao** [bnoguchi/mongoose-auth#38]
The whole error is as follows 

```
Error: Step findOrCreateUser of `facebook` module timed out.
at /home/dotcloud/node_modules/everyauth/lib/step.js:119:18
at Object.<anonymous> (/home/dotcloud/node_modules/everyauth/lib/promise.js:65:27)
at Timer.callback (timers.js:83:39)
```

This is from my staging env hosted on dotcloud. On my local it runs fine. When checking npm list for version numbers, I found that  some of the everyauth submodules were higher version than what was on my local. (Everyauth version was the same). 

Local: (not sure why connect-redis is there)

```
├─┬ everyauth@0.2.18 
│ ├─┬ connect@1.6.1 
│ │ ├─┬ connect-redis@1.0.6  extraneous
│ │ │ └── UNMET DEPENDENCY redis >= 0.0.1
│ │ ├── mime@1.2.2 
│ │ └── qs@0.3.0 
│ ├── oauth@0.9.3 
│ ├── openid@0.1.8 
│ ├── restler@0.2.1 
│ └─┬ xml2js@0.1.9 
│   └── sax@0.2.3 
```

dotcloud:

```
├─┬ everyauth@0.2.18 
│ ├─┬ connect@1.6.2 
│ │ ├── mime@1.2.2 
│ │ └── qs@0.3.0 
│ ├── oauth@0.9.4 
│ ├── openid@0.1.8 
│ ├── restler@0.2.1 
│ └─┬ xml2js@0.1.9 
│   └── sax@0.2.3 
```

Would the different versions have anything to do with the error? I overrode `findOrCreateUser` so could it be a problem with my code, even if it works on my local?  I'm pretty new to node, so a push in the right direction would be a big help :)

Thanks!

**Comment by bnoguchi** [comment]
Can you copy/paste your findOrCreateUser code?

**Comment by jamiltao** [comment]
Put the code in this gist:

https://gist.github.com/1148682

**Comment by bnoguchi** [comment]
Is Mongo running on dotcloud? A timeout will happen if any of the async calls never invoke a callback.

**Comment by jamiltao** [comment]
good call, it was actually a permissions problem in the mongo instance (when dotcloud created the db, the root user didn't have read access to the db)

Thanks!
