### ISSUE TITLE
Install Error On "mongoose-types" Dependency

### ISSUE THREAD

**Issue by busticated** [bnoguchi/mongoose-auth#4]
When installing via NPM, I get an error: "Required package: mongoose-types(>=1.0.3) not found."

If I install mongoose-types via npm first, I am then able to install mongoose-auth without issue.

Here's the full log:
`npm install mongoose-auth
npm info it worked if it ends with ok
npm info using npm@0.3.18
npm info using node@v0.4.6
npm info preinstall mongoose-auth@0.0.5
npm ERR! install failed Error: Required package: mongoose-types(>=1.0.3) not found.
npm ERR! install failed (required by: mongoose-auth@0.0.5)
npm ERR! install failed     at /usr/local/lib/node/.npm/npm/0.3.18/package/lib/build.js:185:27
npm ERR! install failed     at cb (/usr/local/lib/node/.npm/npm/0.3.18/package/lib/utils/graceful-fs.js:31:9)
npm info install failed rollback
npm info uninstall [ 'mongoose-auth@0.0.5' ]
npm info preuninstall mongoose-auth@0.0.5
npm info uninstall mongoose-auth@0.0.5
npm info auto-deactive not symlink
npm info postuninstall mongoose-auth@0.0.5
npm info uninstall mongoose-auth@0.0.5 complete
npm info install failed rolled back
npm ERR! Error: Required package: mongoose-types(>=1.0.3) not found.
npm ERR! (required by: mongoose-auth@0.0.5)
npm ERR!     at /usr/local/lib/node/.npm/npm/0.3.18/package/lib/build.js:185:27
npm ERR!     at cb (/usr/local/lib/node/.npm/npm/0.3.18/package/lib/utils/graceful-fs.js:31:9)
npm ERR! Report this *entire* log at <http://github.com/isaacs/npm/issues>
npm ERR! or email it to <npm-@googlegroups.com>
npm ERR! Just tweeting a tiny part of the error will not be helpful.
npm ERR! System Darwin 10.6.0
npm ERR! argv { remain: 
npm ERR! argv    [ 'mongoose-auth',
npm ERR! argv      'bcrypt@>=0.2.0',
npm ERR! argv      'mongoose@>=1.2.0',
npm ERR! argv      'everyauth@>=0.0.9' ],
npm ERR! argv   cooked: [ 'install', 'mongoose-auth' ],
npm ERR! argv   original: [ 'install', 'mongoose-auth' ] }
npm not ok`

**Comment by bnoguchi** [comment]
It works for me. What version of npm are you on? I'm on 1.0.1@rc9.

**Comment by busticated** [comment]
ah... that's likely the issue. I'm still rockin' 0.3.18

**Comment by bnoguchi** [comment]
Yeah, definitely upgrade to 1.x since there are major architectural changes from 0.3.x to 1.x.
