### ISSUE TITLE
everyauth is not defined

### ISSUE THREAD

**Issue by douglasgraves** [bnoguchi/mongoose-auth#41]
I've attempted installing mongoose-auth in one of my projects, but haven't managed to figure out how to resolve the "everyauth is not defined" template error that I get when attempting to duplicate a simpler version of your included example in my own project.  I'm also unable to get the drop in routes for /login and /register working, they just 404.

I'm still rather new at node.js, so this is likely not a mongoose-auth issue but a problem of my own making—I likely have something simple misconfigured or some other such issue that I've not quite grasped yet.  Still, I'd really like to understand the problem and learn from it, so if you could point me in the right direction I'd be very appreciative.

My project (an express app) is [here](https://github.com/douglasgraves/skelenode), and after running the server.js file, you should be able to see the template error by going to http://localhost:8081/.

Thanks in advance for your help!

**Comment by afeezaziz** [comment]
Hey @douglasgraves , do you know what is the cause of the problem? Im having the same problem but instead,  Cannot read property 'auth' of undefined .

**Comment by douglasgraves** [comment]
Nope, I just gave up and moved on with my life.  You have any luck?

**Comment by lfalvarez** [comment]
if this is still on I found that reinstalling everyauth does it. I found it in this [issue](https://github.com/bnoguchi/everyauth/issues/221)
