### ISSUE TITLE
Step registerUser of `password` module timed out.

### ISSUE THREAD

**Issue by alfrednerstu** [bnoguchi/mongoose-auth#46]
I'm trying out mongoose-auth and I get this error:

127.0.0.1 - - [Fri, 16 Sep 2011 13:44:07 GMT] "GET /register HTTP/1.1" 200 772 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_7_0) AppleWebKit/535.1 (KHTML, like Gecko) Chrome/14.0.835.163 Safari/535.1"
{ stack: [Getter/Setter],
  arguments: undefined,
  type: undefined,
  message: 'Step registerUser of `password` module timed out.' }
Error: Step registerUser of `password` module timed out.
    at /Users/Alfred/Sites/note0/node_modules/mongoose-auth/node_modules/everyauth/lib/step.js:121:18
    at Object.<anonymous> (/Users/Alfred/Sites/note0/node_modules/mongoose-auth/node_modules/everyauth/lib/promise.js:65:27)
    at Timer.callback (timers.js:83:39)

Know what it could be?

**Comment by robertjd** [comment]
I've also been seeing this problem, but only in my dev environment on OSX 10.7

**Comment by nnarasimha** [comment]
I am facing the same issue. Any updates on this?

**Comment by furtivefelon** [comment]
i have the same issue as well, any updates?

**Comment by andrewfhart** [comment]
This happened to me at one point, but (for me at least) it was caused by not having any MongoDB instance running at the time.  Since no connection could be established, the step eventually timed out. Starting `mongod` fixed it for me...

**Comment by furtivefelon** [comment]
well that was very dumb of me... I didn't install mongodb on the dev side

Thanks a lot for your help Andrew :)

**Comment by irimawi** [comment]
This happens to me even though mongodb is running in the background and the application is able to get some data. Also, I noticed I am able to login using mongoose-auth, happening with registering new users. changing everyauth timeout to big number or -1 (disable timeout) makes the browser spin with no status changes. I really appreciate any help on this one
