### ISSUE TITLE
Connecting multiple accounts

### ISSUE THREAD

**Issue by balupton** [bnoguchi/mongoose-auth#5]
Hey :) GREAT WORK!

Is it possible to connect multiple accounts to the one user? I'm thinking if their email matches they can be merged, or if the user is logged in, then it automatically connects/merges rather than creating a new user.

Thoughts?

**Comment by tixelated** [comment]
+1. Simpler functionality would suffice, too - could simply use the currently-authenticated user, and link in the new account (e.g. login with Facebook, then connect to Twitter, or login with Password, then connect to Facebook/Twitter/etc)

**Comment by bnoguchi** [comment]
Yeah, this is actually really straightforward. The real magic lies with https://github.com/bnoguchi/everyauth/, and it should be more obvious once I document everyauth more and document mongoose-auth's relationship to everyauth.

In everyauth's design, every auth module is defined as a set of steps, which are exposed in such a way for you to over-ride. The step that is of particular interest for this scenario is the `findOrCreateUser` step required by every `everyauth` module.  `mongoose-auth` defines a default version of this `findOrCreateUser` step for each everyauth auth module it supports (You can find these default definitions in "lib/modules/#{moduleName}/everyauth.js" -- e.g., see `lib/modules/facebook/everyauth.js`). So for example, this is how you would over-ride the default `findOrCreateUser` step for the facebook module if you are using both the facebook and password module:

``` javascript
var Promise = everyauth.Promise;

UserSchema.plugin(mongooseAuth, {
  facebook: {
    everyauth: {
        myHostname: ...
      , ...
      , findOrCreateUser: function (session, accessTok, accessTokExtra, fbUser) {
          var promise = new Promise()
              , User = this.User()();
          User.findById(session.auth.userId, function (err, user) {
            if (err) return promise.fail(err);
            if (!user) {
              User.where('password.login', fbUser.email).findOne( function (err, user) {
                if (err) return promise.fail(err);
                if (!user) {
                  User.createWithFB(fbUser, accessTok, accessTokExtra.expires, function (err, createdUser) {
                    if (err) return promise.fail(err);
                    return promise.fulfill(createdUser);
                  });
                } else {
                  assignFbDataToUser(user, accessTok, accessTokExtra, fbUser);
                  user.save( function (err, user) {
                    if (err) return promise.fail(err);
                    promise.fulfill(user);
                  });
                }
              });
            } else {
              assignFbDataToUser(user, accessTok, accessTokExtra, fbUser);

              // Save the new data to the user doc in the db
              user.save( function (err, user) {
                if (err) return promise.fail(err);
                promise.fuilfill(user);
              });
            }
          });
        });
        return promise; // Make sure to return the promise that promises the user
      }
  }
});

// Assign all properties - see lib/modules/facebook/schema.js for details
function assignFbDataToUser (user, accessTok, accessTokExtra, fbUser) {
  user.fb.accessToken = accessTok;
  user.fb.expires = accessTokExtra.expires;
  user.fb.id = fbUser.id;
  user.fb.name.first = fbUser.first_name;
  // etc. more assigning...
}
```

As this is a common recipe, I plan on adding support for this into `everyauth` and `mongoose-auth`, so it's more drop-in, and developers do not have to add this custom code themselves. The intent is for common things like this to be invisible to the developer, so it just "works like magic." So, in the near future, you won't have to over-ride the findOrCreateUser step every time you want this feature. This will be coming soon.

Let me know if this needs more clarification.

**Comment by tblobaum** [comment]
Hmm, I'm trying to get multiple accounts to work, and I have had success getting all of the data into mongo.  However, I keep getting an "expires" of "Thu, 01 Jan 1970 00: 00: 05 +0000" which can't be right... Is the expires field necessary for anything? Here is the code, with a note.

function assignFbDataToUser (user, accessTok, accessTokExtra, fbUser) {
    user.fb.accessToken = accessTok;
    user.fb.expires = accessTokExtra.expires; 
// returns "Thu, 01 Jan 1970 00: 00: 05 +0000" -- coming from line 11, 12 of modules/facebook/plugin.js
    user.fb.id = fbUser.id;
    user.fb.name.full = fbUser.name;
    user.fb.name.first = fbUser.first_name;
    user.fb.name.last = fbUser.last_name;
    user.fb.fbAlias = fbUser.link.match(/^http:\/\/www.facebook.com\/(.+)/)[1],
    user.fb.gender = fbUser.gender;
    user.fb.email = fbUser.email;
    user.fb.timezone = fbUser.timezone;
    user.fb.locale = fbUser.locale;
    user.fb.verified = fbUser.verified;
    user.fb.phone = fbUser.phone;
    user.fb.updatedTime = fbUser.updated_time;
}

findOrCreateUser: function (session, accessTok, accessTokExtra, fbUser) {
    var promise = this.Promise()
    , User = this.User()();
    User.findById(session.auth.userId, function (e, user) {
        if (e) return promise.fail(e);
        if (!user) {
            User.where('password.login', fbUser.email).findOne( function (e, user) {
                if (e) return promise.fail(e);
                if (!user) {
                    User.createWithFB(fbUser, accessTok, accessTokExtra.expires, function (e, createdUser) {
                        if (e) return promise.fail(e);
                        return promise.fulfill(createdUser);
                    });
                } else {
                    assignFbDataToUser(user, accessTok, accessTokExtra, fbUser);
                    user.save( function (e, user) {
                        if (e) return promise.fail(e);
                        promise.fulfill(user);
                    });
                }
            });
        } else {
            assignFbDataToUser(user, accessTok, accessTokExtra, fbUser);
            user.save( function (e, user) {
                if (e) return promise.fail(e);
                promise.fulfill(user);
            });
        }
    });
    return promise;
}
