### ISSUE TITLE
node 0.6.0 segmentation fault

### ISSUE THREAD

**Issue by tblobaum** [bnoguchi/mongoose-auth#55]
I'm not sure what is causing this but I'm seeing it in 0.6.0 and 0.6.1.  I have a pretty simple app using mongoose auth and when trying to login node exits with nothing but "Segmentation fault."

**Comment by jonbuffington** [comment]
FWIW, I experienced similar symptoms and tracked the root cause to a threading issue in the bcrypt library. The bcrypt library author has patched the library.

**Comment by tblobaum** [comment]
Looks like that was it @jonbuffington thanks.

**Comment by donflopez** [comment]
I have the same problem and i've patched the library without any result.

**Comment by tblobaum** [comment]
@donflopez try running `npm rebuild`

**Comment by donflopez** [comment]
@tblobaum Thankyou!
