### ISSUE TITLE
Access to User db object

### ISSUE THREAD

**Issue by ghost** [bnoguchi/mongoose-auth#6]
Hey there - wondering how to get access to the actual DB User record that's linked to the facebook/twitter/etc account info. That is, once a user logs in (using, say, facebook,) I know I can get at their facebook info from req.session.auth.facebook, but not that actual user record.

I just wanted to check and make sure there isn't a way already built to do this before getting into querying for that user record via the facebook embedded document, which is otherwise the only way I know how to do it...

**Comment by tixelated** [comment]
More info - my req.session after a successful facebook authentication looks like this:

```
{
  "lastAccess":1303841289370,
  "cookie":{
    "originalMaxAge":14400000,
    "expires":"2011-04-26T22:07:38.878Z",
    "httpOnly":true,
    "path":"/"
  },
  "auth":{
    "facebook":{
      "user":{
        "id":"610771581",
        "name":"Jason Bond Pratt",
        "first_name":"Jason",
        "middle_name":"Bond",
        "last_name":"Pratt",
        "link":"http://www.facebook.com/jasonbondpratt",
        "username":"jasonbondpratt",
        "hometown":{
          "id":"107442005952063",
          "name":"Hartford, Michigan"
        },
        "location":{
          "id":"110184922344060",
          "name":"Washington, District of Columbia"
        },
        "gender":"male",
        "email":"facebook@juniorplenty.com",
        "timezone":-4,
        "locale":"en_US",
        "verified":true,
        "updated_time":"2011-04-16T22:09:12+0000"
      },
      "accessToken":"XXXXXXXXXXXXXXXXXXXXX"
    },
    "loggedIn":true
  }
}
```

**Comment by bnoguchi** [comment]
Rolling out a req.user accessor within the hour. Stay tuned.

**Comment by bnoguchi** [comment]
npm install the latest v0.0.6

From your express server code, you now will have access to `req.user`

From your express views, you now will have access to both
- `everyauth.user`
- `user`

which equivalently return the mongoose User document associated with the current session

**Comment by tixelated** [comment]
AWESOME.

**Comment by tixelated** [comment]
This is great - originally I had some problems, as I missed the update in everyauth that requires the findUserById function to be defined, works great now. That being said - maybe mongoose-auth could provide that definition by default, since it has access to the User model (via it's configurable User function) and knows that it's using Mongoose. Anyway just an idea.

**Comment by bnoguchi** [comment]
mongoose-auth does provide a default findUserById definition. If you check the README, you do not have to define findUserById for mongoose-auth, since it does it for you automatically.
