### ISSUE TITLE
Can't override findOrCreateUser ?

### ISSUE THREAD

**Issue by felixchan** [bnoguchi/mongoose-auth#7]
Thanks for building this module, I really like! But I've ran into a prob.

This may not be a bug, as I think I'm just inexperienced.
Anyway,  I want to over-ride findOrCreateUsers, because I want to assign each new user a random "code" upon signup, and put it inside their db.users profile as a field, "code".

I read the documentation, and saw that you could override findOrCreateUser. So I did that:

```
//Begin User Login----------------
var UserSchema = new Schema({}), User;
var Promise = everyauth.Promise;
UserSchema.plugin(mongooseAuth,{
        everymodule: {
          everyauth: {
              User: function () {
                return User;
              }   
          }   
        }   
      , facebook: {
          everyauth: {
                myHostname: settings.fb.hostname,
                appId: settings.fb.fbAppId,
                appSecret: settings.fb.fbSecret,
                scope: settings.fb.fbScope,
                entryPath: "/account/facebook/auth",
                redirectPath: '/account/prep',
                findOrCreateUser: function (sess, accessTok, accessTokExtra, fbUser) {
                    var promise = new Promise(), self = this;
                    this.User()().findOne({'fb.id': fbUser.id}, function (err, foundUser) {
                      if (foundUser)
                        return promise.fulfill(foundUser);
                      self.User()().createWithFB(fbUser, accessTok, accessTokExtra.expires, function (err, createdUser) {
                        return promise.fulfill(createdUser);
                      }); 
                    }); 
                    return promise;
                }   
        }   
    }   
}); 
mongoose.model("User", UserSchema);
var User = mongoose.model("User")
//End User Login--------------------
```

I copied and pasted what was in "mongoose-auth/lib/facebook/" into my app.js. (above, you see the copied code).

Everything works, and I'm able to login/create a user!! However, the only problem is that after the redirectPath, "req.user" is undefined.  "req.loggedIn" says it's true, but req.user is undefined.

**Comment by bnoguchi** [comment]
What version of mongoose-auth and everyauth are you using?

**Comment by felixchan** [comment]
thanks for the response!! :)

I'm using the latest versions of mongoose-auth, everyauth, and mongoose.
I even removed the modules and npm installed agan.

**Comment by bnoguchi** [comment]
Can you also send over a complete gist (https://gist.github.com) because I have not been able to re-produce the `req.user` === undefined result that you are getting?

**Comment by bnoguchi** [comment]
Can you copy/paste the exact versions?

**Comment by felixchan** [comment]
here's the public gist : https://gist.github.com/947677

**Comment by bnoguchi** [comment]
Just fixed this. Now, in your code, just replace the Promise assignment with:

``` javascript
var Promise = mongooseAuth.Promise
```

Should work after that.

--Brian

**Comment by guiomie** [comment]
I am getting the same problem with everyauth and mongoose, what is the equivalent for my set up? (i am not using mongooseAuth)
