### ISSUE TITLE
login should be validated for uniqueness

### ISSUE THREAD

**Issue by theshortcut** [bnoguchi/mongoose-auth#8]
Can workaround by adding `User.path('login').index({ unique: true });` after the `User.plugin(mongooseAuth ...` stuff and then handling the duplicate key errors. It'd be nice if this was built in by default.

**Comment by bnoguchi** [comment]
Yeah, I realized the same oversight recently :P The fix is in a recent series of local commits. Going to push them that all as soon as I finish one last new feature. Should be done by tomorrow night or tomorrow morning. Thanks for the watchful eye. Come back soon for the latest version.

**Comment by tblobaum** [comment]
Brian -- Awesome!

**Comment by bnoguchi** [comment]
Sorry, got busy with the weekend. New version coming tomorrow morning.

**Comment by cayasso** [comment]
Hi Brian, any estimate when the new version will be out, I just don't want to start hacking around when there is a new version to come ;)

Have a great day!!!
JB

**Comment by bnoguchi** [comment]
It's there now :) everyauth v0.2.0 and mongoose-auth v0.0.9

**Comment by tblobaum** [comment]
You rock!
